/** @type {import('stylelint').Config} */
export default {
  extends: 'stylelint-config-obsidianmd',

  // theme.css is generated by build.py from src/, so lint the sources instead.
  ignoreFiles: ['theme.css', 'node_modules/**'],

  rules: {
    // Every offender is a class name we do not own: CodeMirror's
    // .HyperMD-header-N and .cm-contentContainer, and the Page Gallery
    // plugin's BEM .page-gallery__* blocks.
    'selector-class-pattern': null,

    // A theme styles someone else's DOM, so the ordering this rule wants
    // conflicts with the :not() layering the infobox and callout rules rely
    // on. Reordering them to satisfy the linter would change the cascade.
    'no-descending-specificity': null,
  },
};
